
services:
# connect to db container: 
#     docker exec -it mysqldb bash
#     bash: mysql --password="example"
# mysql connection string in Go: 
#     user:password@tcp(container-name:3306)/database

  mysqldb: 
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports: 
      - 8080:8080

volumes:
  mysqldb: